### ISSUE TITLE
Cleanup job fails if topic doesn't have associated schema

### ISSUE THREAD

**Issue by disrupted** [bakdata/streams-bootstrap#186]
The [word-count example pipeline](https://github.com/bakdata/kpops-examples/blob/main/word-count/deployment/kpops/pipeline.yaml) doesn't use topic schemas. When running the streams-app-cleanup-job it fails with
```
com.bakdata.kafka.CleanUpException: Could not reset schema registry for topic word-count-app-word-counter-topic-KSTREAM-AGGREGATE-STATE-STORE-0000000003-repartition
    at com.bakdata.kafka.util.SchemaTopicClient.resetSchemaRegistry(SchemaTopicClient.java:118)
    at java.base/java.util.ArrayList.forEach(Unknown Source)
    at com.bakdata.kafka.CleanUpRunner.run(CleanUpRunner.java:158)
    at com.bakdata.kafka.KafkaStreamsApplication.cleanUpRun(KafkaStreamsApplication.java:334)
    at com.bakdata.kafka.KafkaStreamsApplication.runCleanUp(KafkaStreamsApplication.java:328)
    at com.bakdata.kafka.KafkaStreamsApplication.run(KafkaStreamsApplication.java:121)
    at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
    at picocli.CommandLine.access$1500(CommandLine.java:148)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
    at picocli.CommandLine.execute(CommandLine.java:2170)
    at com.bakdata.kafka.KafkaApplication.startApplicationWithoutExit(KafkaApplication.java:127)
    at com.bakdata.kafka.KafkaApplication.startApplication(KafkaApplication.java:101)
    at com.bakdata.kpops.examples.WordCountApplication.main(WordCountApplication.java:18)
Caused by: java.net.MalformedURLException: no protocol: /subjects
    at java.base/java.net.URL.<init>(Unknown Source)
    at java.base/java.net.URL.<init>(Unknown Source)
    at java.base/java.net.URL.<init>(Unknown Source)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.url(RestService.java:1310)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:279)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:384)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:1037)
    at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:1022)
    at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getAllSubjects(CachedSchemaRegistryClient.java:677)
    at com.bakdata.kafka.util.SchemaTopicClient.resetSchemaRegistry(SchemaTopicClient.java:102)
    ... 16 more
```

**Comment by philipp94831** [comment]
Is a schema registry URL configured?

**Comment by disrupted** [comment]
I believe it is. Shouldn't the SR only be contacted if the topic actually defines a schema?

**Comment by philipp94831** [comment]
Kafka Streams has no way of knowing whether there is a schema for a topic or not without contacting the SR. Therefore we need to check this first. However, there seems to be issues if no SR is configured (which was not intended in the beginning as it is a required parameter https://github.com/bakdata/streams-bootstrap/blob/6efbd4179af43dd2be89d4e7f1f05a956eb6aee6/src/main/java/com/bakdata/kafka/KafkaApplication.java#L83). Maybe the empty default circumvents that

**Comment by disrupted** [comment]
Ok, understand. How can we solve this? Should `--schema-registry-url` become an optional flag?

**Comment by philipp94831** [comment]
I guess that makes sense
